mainapp/urls.py
from django.contrib import admin
from django.urls import path, include

from tests.views import index

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='index'),
    path('users/', include('users.urls', namespace='users')),
    path('tests/', include('tests.urls', namespace='tests')),
]

users/urls.py
from django.urls import path
from users.views import LoginLoginView, LogoutLogoutView, RegistrationCreateView

app_name = 'users'

urlpatterns = [
    path('login/', LoginLoginView.as_view(), name='login'),
    path('registration/', RegistrationCreateView.as_view(), name='registration'),
    path('logout/', LogoutLogoutView.as_view(), name='logout'),
]

questions/models.py
from django.db import models


class Answer(models.Model):
    name = models.CharField(max_length=256, blank=True)
    is_right = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Question(models.Model):
    name = models.CharField(max_length=256, blank=True)
    answers = models.ManyToManyField(Answer, blank=True)

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from tests.models import Test


class User(AbstractUser):
    current_test = models.JSONField(blank=True, null=True)


class UserStatistic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.SET_NULL, null=True)
    result = models.IntegerField(default=0)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
import random
import hashlib

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите email'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

questions/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import UserLoginForm, UserRegistrationForm
from users.models import User


class LoginLoginView(LoginView):
    model = User
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('tests:index')


class RegistrationCreateView(CreateView):
    model = User
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('tests:index')


class LogoutLogoutView(LogoutView):
    next_page = 'index'

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Signin Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">


    <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }





    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/sign-in.css' %}" rel="stylesheet">
</head>
<body class="text-center">
{% block content %} {% endblock %}

</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
{% load static %}

<main class="form-signin w-100 m-auto">
    {% if messages or form.errors %}
    <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %}alert-dismissible fade show"
         role="alert"
         style="margin-top: 50px;">
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% else %}
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
        {% endif %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}

        <img class="mb-4" src="{% static 'assets/brand/bootstrap-logo.svg' %}" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Вход</h1>

        <div class="form-floating">
            {{ form.username }}
            <label for="floatingInput">Имя пользователя</label>
        </div>
        <div class="form-floating">
            {{ form.password }}
            <label for="floatingPassword">Пароль</label>
        </div>

        <div class="card-footer text-center">
            <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2022</p>
    </form>
</main>

{% endblock %}

users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block content %}
{% load static %}


<main class="form-signin w-100 m-auto">
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert"
         style="margin-top: 50px;">
        {{ form.errors }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    <form action="{% url 'users:registration' %}" method="post">
        {% csrf_token %}

        <img class="mb-4" src="{% static 'assets/brand/bootstrap-logo.svg' %}" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Регистрация</h1>

        <div class="form-floating">
            {{ form.first_name }}
            <label for="{{ form.first_name.id_for_label }}">Имя</label>
        </div>
        <div class="form-floating">
            {{ form.last_name }}
            <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
        </div>
        <div class="form-floating">
            {{ form.username }}
            <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
        </div>
        <div class="form-floating">
            {{ form.email }}
            <label for="{{ form.email.id_for_label }}">Адрес электронной
                почты</label>
        </div>
        <div class="form-floating">
            {{ form.password1 }}
            <label for="{{ form.password1.id_for_label }}">Пароль</label>
        </div>
        <div class="form-floating">
            {{ form.password2 }}
            <label for="{{ form.password2.id_for_label }}">Подтверждение
                пароля</label>
        </div>


        <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2022</p>
    </form>
</main>


{% endblock %}

users/templates/users/statistic.html
{% extends 'tests/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/categories.css'%}" rel="stylesheet">
<link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/grid/">


<link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

</style>
<link href="{% static 'css/grid.css' %}" rel="stylesheet">

{% endblock %}
{% block content %}
<!-- Page Content -->
<div class="container">


    <h2 class="mt-4">Ваша статистика</h2>
    {% for test in tests %}
    <div class="row mb-3 text-center">
        <div class="col-sm-6 col-lg-8 themed-grid-col">{{ test.test }}</div>
        <div class="col-6 col-lg-4 themed-grid-col">{{ test.result }}</div>
    </div>
    {% endfor %}


</div>
<!-- /.container -->



{% endblock %}